let cleanData = [   
    {
        id: 11,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "WASHCLEAN 6 kg",
        unit: "kg",
        amount: 6,
        shortDescription: "Silně alkalický, nepěnivý čistící a odmašťující přípravek",
        img: "/img/washclean 6 L.png",
        longDescription: "Silně alkalický, nepěnivý čistící a odmašťující přípravek. Používá se na vodovzdorné povrchy, podlahy a technologická zařízení v potravinářství, stravovacích provozech, bazénech, kotelnách k vnitřnímu čištění potrubí a nádrží, apod.",
        preicePerKg: "19900",
        pricePerKgVat: "24070",
        pricePerUnit: "119400",
        pricePerUnitVat: "144474",
        howToUse: "Generální úklid a odmaštění: smíchejte s vodou v poměru 1:1 – 1:20 (5 dl na 10 l vody). Běžný úklid: smíchejte s vodou v poměru 1:100 (1dl na 10 l vody).",
        dataSheet: "/downloads/washclean data.pdf",
        properties: "Světležlutá kapalina, pH 11,0-13,5 (3% roztok při 20 °C). Zápach: slabý, charakteristický.",
        safetySheet: "/downloads/washclean safety.pdf"
    },
    {
        id: 12,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "WASHCLEAN 30 kg",
        unit: "kg",
        amount: 30,
        shortDescription: "Silně alkalický, nepěnivý čistící a odmašťující přípravek",
        img: "/img/washclean 30 L.png",
        longDescription: "Silně alkalický, nepěnivý čistící a odmašťující přípravek. Používá se na vodovzdorné povrchy, podlahy a technologická zařízení v potravinářství, stravovacích provozech, bazénech, kotelnách k vnitřnímu čištění potrubí a nádrží, apod.",
        preicePerKg: "17900",
        pricePerKgVat: "21659",
        pricePerUnit: "537000",
        pricePerUnitVat: "649770",
        howToUse: "Generální úklid a odmaštění: smíchejte s vodou v poměru 1:1 – 1:20 (5 dl na 10 l vody). Běžný úklid: smíchejte s vodou v poměru 1:100 (1dl na 10 l vody).",
        dataSheet: "/downloads/washclean data.pdf",
        properties: "Světležlutá kapalina, pH 11,0-13,5 (3% roztok při 20 °C). Zápach: slabý, charakteristický.",
        safetySheet: "/downloads/washclean safety.pdf"
    },
    {
        id: 13,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "FLOORWASH 6 kg",
        unit: "kg",
        amount: 6,
        shortDescription: "Alkalický, nepěnivý, čistící a odmašťující přípravek",
        img: "/img/floorwash 6 L.png",
        longDescription: "Alkalický, nepěnivý, čistící a odmašťující přípravek. Používá se na vodovzdorné povrchy, podlahy a technologická zařízení. Vhodný i pro odstranění podlahových vosků v tělocvičnách, školách, k odstranění šmouh od obuvi, komunálních budovách apod. Také odstraňuje pryskyřici z dřevěných podlah, hoblovek a pilových listů.",
        preicePerKg: "20900",
        pricePerKgVat: "25289",
        pricePerUnit: "125400",
        pricePerUnitVat: "151734",
        howToUse: "Generální úklid a odmaštění: smíchejte s vodou v poměru 1:1 – 1:20 (5 dl na 10 l vody) v závislosti na znečištění. Odstranění podlahových vosků: smíchejte s vodou v poměru 1:40 (2,5 dl na 10 l vody) s teplou vodou. Odstranění pryskyřice: aplikujte rozprašovačem, houbou apod. Nechte působit a poté setřete vlhkým hadříkem. Běžný úklid: smíchejte s vodou v poměru 1:100 (1dl na 10 l vody).",
        dataSheet: "/downloads/floorwash data.pdf",
        properties: "Bezbarvá kapalina. Hodnota pH (20 °C): 13,5. Bez zápachu.",
        safetySheet: "/downloads/floorwash safety.pdf"
    },
    {
        id: 14,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "FLOORWASH 30 kg",
        unit: "kg",
        amount: 30,
        shortDescription: "Alkalický, nepěnivý, čistící a odmašťující přípravek",
        img: "/img/floorwash 30 L.png",
        longDescription: "Alkalický, nepěnivý, čistící a odmašťující přípravek. Používá se na vodovzdorné povrchy, podlahy a technologická zařízení. Vhodný i pro odstranění podlahových vosků v tělocvičnách, školách, k odstranění šmouh od obuvi, komunálních budovách apod. Také odstraňuje pryskyřici z dřevěných podlah, hoblovek a pilových listů.",
        preicePerKg: "18600",
        pricePerKgVat: "22506",
        pricePerUnit: "558000",
        pricePerUnitVat: "675180",
        howToUse: "Generální úklid a odmaštění: smíchejte s vodou v poměru 1:1 – 1:20 (5 dl na 10 l vody) v závislosti na znečištění. Odstranění podlahových vosků: smíchejte s vodou v poměru 1:40 (2,5 dl na 10 l vody) s teplou vodou. Odstranění pryskyřice: aplikujte rozprašovačem, houbou apod. Nechte působit a poté setřete vlhkým hadříkem. Běžný úklid: smíchejte s vodou v poměru 1:100 (1dl na 10 l vody).",
        dataSheet: "downloads/floorwash data.pdf",
        properties: "Bezbarvá kapalina. Hodnota pH (20 °C): 13,5. Bez zápachu.",
        safetySheet: "/downloads/floorwash safety.pdf"
    },
    {
        id: 15,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "GASTRO CLEAN 30 kg",
        unit: "kg",
        amount: 30,
        shortDescription: "Silně alkalický, nepěnivý čistící a odmašťující přípravek pro všechny typy myček nádobí",
        img: "/img/gastro clean 30 L.png",
        longDescription: "Silně alkalický, nepěnivý čistící a odmašťující přípravek pro všechny typy myček nádobí s možností ručního i automatického dávkování. Silný koncentrát bez nepříjemného zápachu. Odstraňuje zbytky jídel všeho druhu. Nepoužívat na hliníkové nádobí z důvodu vzniku možné koroze.",
        preicePerKg: "13900",
        pricePerKgVat: "16819",
        pricePerUnit: "417000",
        pricePerUnitVat: "504570",
        howToUse: "Dávkujte 1-3 ml na 1 l vody. Záleží na tvrdosti vody. V případě velké tvrdosti vody zvyšte dávkování dle potřeby.",
        dataSheet: "/downloads/gastro clean data.pdf",
        properties: "Světležlutá kapalina, pH 11,0-13,5 (3% roztok při 20 °C). Zápach: slabý, charakteristický.",
        safetySheet: "/downloads/gastro clean safety.pdf"
    },

];

/* Template
    {
        id: 11,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "",
        unit: "",
        amount: 1,
        shortDescription: "",
        img: "/img/canister.jpg",
        longDescription: "",
        preicePerKg: "",
        pricePerKgVat: "",
        pricePerUnit: "",
        pricePerUnitVat: "",
        howToUse: "",
        dataSheet: "",
        properties: "",
        safetySheet: ""
    },
*/