let cleanData = [   
    {
        id: 11,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "WASHCLEAN 6 kg",
        unit: "kg",
        amount: 6,
        shortDescription: "Silně alkalický, nepěnivý čistící a odmašťující přípravek",
        img: "/img/washclean 6.png",
        longDescription: "Silně alkalický, nepěnivý čistící a odmašťující přípravek. Používá se na vodovzdorné povrchy, podlahy a technologická zařízení v potravinářství, stravovacích provozech, bazénech, kotelnách k vnitřnímu čištění potrubí a nádrží, apod.",
        preicePerKg: "19900",
        pricePerKgVat: "24070",
        pricePerUnit: "119400",
        pricePerUnitVat: "144474",
        howToUse: "Generální úklid a odmaštění: smíchejte s vodou v poměru 1:1 – 1:20 (5 dl na 10 l vody). Běžný úklid: smíchejte s vodou v poměru 1:100 (1dl na 10 l vody).",
        dataSheet: "/downloads/washclean data.pdf",
        properties: "Světležlutá kapalina, pH 11,0-13,5 (3% roztok při 20 °C). Zápach: slabý, charakteristický.",
        safetySheet: "/downloads/washclean safety.pdf"
    },
    {
        id: 12,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "WASHCLEAN 30 kg",
        unit: "kg",
        amount: 30,
        shortDescription: "Silně alkalický, nepěnivý čistící a odmašťující přípravek",
        img: "/img/washclean 30.png",
        longDescription: "Silně alkalický, nepěnivý čistící a odmašťující přípravek. Používá se na vodovzdorné povrchy, podlahy a technologická zařízení v potravinářství, stravovacích provozech, bazénech, kotelnách k vnitřnímu čištění potrubí a nádrží, apod.",
        preicePerKg: "17900",
        pricePerKgVat: "21659",
        pricePerUnit: "537000",
        pricePerUnitVat: "649770",
        howToUse: "Generální úklid a odmaštění: smíchejte s vodou v poměru 1:1 – 1:20 (5 dl na 10 l vody). Běžný úklid: smíchejte s vodou v poměru 1:100 (1dl na 10 l vody).",
        dataSheet: "/downloads/washclean data.pdf",
        properties: "Světležlutá kapalina, pH 11,0-13,5 (3% roztok při 20 °C). Zápach: slabý, charakteristický.",
        safetySheet: "/downloads/washclean safety.pdf"
    },
    {
        id: 13,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "FLOORWASH 6 kg",
        unit: "kg",
        amount: 6,
        shortDescription: "Alkalický, nepěnivý, čistící a odmašťující přípravek",
        img: "/img/floorwash 6.png",
        longDescription: "Alkalický, nepěnivý, čistící a odmašťující přípravek. Používá se na vodovzdorné povrchy, podlahy a technologická zařízení. Vhodný i pro odstranění podlahových vosků v tělocvičnách, školách, k odstranění šmouh od obuvi, komunálních budovách apod. Také odstraňuje pryskyřici z dřevěných podlah, hoblovek a pilových listů.",
        preicePerKg: "20900",
        pricePerKgVat: "25289",
        pricePerUnit: "125400",
        pricePerUnitVat: "151734",
        howToUse: "Generální úklid a odmaštění: smíchejte s vodou v poměru 1:1 – 1:20 (5 dl na 10 l vody) v závislosti na znečištění. Odstranění podlahových vosků: smíchejte s vodou v poměru 1:40 (2,5 dl na 10 l vody) s teplou vodou. Odstranění pryskyřice: aplikujte rozprašovačem, houbou apod. Nechte působit a poté setřete vlhkým hadříkem. Běžný úklid: smíchejte s vodou v poměru 1:100 (1dl na 10 l vody).",
        dataSheet: "/downloads/floorwash data.pdf",
        properties: "Bezbarvá kapalina. Hodnota pH (20 °C): 13,5. Bez zápachu.",
        safetySheet: "/downloads/floorwash safety.pdf"
    },
    {
        id: 14,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "FLOORWASH 30 kg",
        unit: "kg",
        amount: 30,
        shortDescription: "Alkalický, nepěnivý, čistící a odmašťující přípravek",
        img: "/img/floorwash 30.png",
        longDescription: "Alkalický, nepěnivý, čistící a odmašťující přípravek. Používá se na vodovzdorné povrchy, podlahy a technologická zařízení. Vhodný i pro odstranění podlahových vosků v tělocvičnách, školách, k odstranění šmouh od obuvi, komunálních budovách apod. Také odstraňuje pryskyřici z dřevěných podlah, hoblovek a pilových listů.",
        preicePerKg: "18600",
        pricePerKgVat: "22506",
        pricePerUnit: "558000",
        pricePerUnitVat: "675180",
        howToUse: "Generální úklid a odmaštění: smíchejte s vodou v poměru 1:1 – 1:20 (5 dl na 10 l vody) v závislosti na znečištění. Odstranění podlahových vosků: smíchejte s vodou v poměru 1:40 (2,5 dl na 10 l vody) s teplou vodou. Odstranění pryskyřice: aplikujte rozprašovačem, houbou apod. Nechte působit a poté setřete vlhkým hadříkem. Běžný úklid: smíchejte s vodou v poměru 1:100 (1dl na 10 l vody).",
        dataSheet: "downloads/floorwash data.pdf",
        properties: "Bezbarvá kapalina. Hodnota pH (20 °C): 13,5. Bez zápachu.",
        safetySheet: "/downloads/floorwash safety.pdf"
    },
    {
        id: 15,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "GASTRO CLEAN 30 kg",
        unit: "kg",
        amount: 30,
        shortDescription: "Čistící a odmašťující přípravek pro všechny typy myček nádobí",
        img: "/img/gastro clean 30.png",
        longDescription: "Silně alkalický, nepěnivý čistící a odmašťující přípravek pro všechny typy myček nádobí s možností ručního i automatického dávkování. Silný koncentrát bez nepříjemného zápachu. Odstraňuje zbytky jídel všeho druhu. Nepoužívat na hliníkové nádobí z důvodu vzniku možné koroze.",
        preicePerKg: "13900",
        pricePerKgVat: "16819",
        pricePerUnit: "417000",
        pricePerUnitVat: "504570",
        howToUse: "Dávkujte 1-3 ml na 1 l vody. Záleží na tvrdosti vody. V případě velké tvrdosti vody zvyšte dávkování dle potřeby.",
        dataSheet: "/downloads/gastro clean data.pdf",
        properties: "Světležlutá kapalina, pH 11,0-13,5 (3% roztok při 20 °C). Zápach: slabý, charakteristický.",
        safetySheet: "/downloads/gastro clean safety.pdf"
    },
    {
        id: 16,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "SOFT FLOOR 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Čisticí přípravek na koberce a interiéry aut, linoleum, dlažbu",
        img: "/img/soft floor 5.png",
        longDescription: "Používá se na odstranění nečistot. Vhodné zejména pro čištění linolea, dlažba, koberce. Velice se osvědčil při čištění interiérů automobilů. Účinně odstraňuje mastnotu a zanechává dlouhotrvající vůni. Neobsahuje fosfáty.",
        preicePerKg: "17900",
        pricePerKgVat: "21659",
        pricePerUnit: "89500",
        pricePerUnitVat: "108295",
        howToUse: "Aplikuje se pomocí nízkotlakového pěnovacího zařízení, rozprašovače apod. Teplota vody 0° - 80°C. Po aplikaci se přípravek nechá působit cca 5 minut. Před zaschnutím opláchnout čistou vodou. Nejlépe funguje při použití teplé vody. S opatrností může být používán na hliník a jiné alkalitám neodolné materiály. Dávkování: 1l: 50 l vody.",
        dataSheet: "",
        properties: "",
        safetySheet: "/downloads/soft floor safety.pdf"
    },
    {
        id: 17,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "SPRING 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Mycí přípravek pro ruční mytí nádobí s vůní limetky",
        img: "/img/spring 5.png",
        longDescription: "Mycí přípravek pro ruční mytí nádobí s vůní limetky. Účinně rozpouští mastnotu, oleje a nečistoty.",
        preicePerKg: "6500",
        pricePerKgVat: "7865",
        pricePerUnit: "32500",
        pricePerUnitVat: "39325",
        howToUse: "Běžné mytí nádobí: 1 ml na 5 l vody do dřezu. Na čištění povrchů: 5 ml na 5 l vody.",
        dataSheet: "",
        properties: "",
        safetySheet: "/downloads/spring safety.pdf"
    },
    {
        id: 18,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "RUDON 6 kg",
        unit: "kg",
        amount: 6,
        shortDescription: "Pěnivý čistící přípravek na odstranění tuků, napečenin atd.",
        img: "/img/rudon 6.png",
        longDescription: "Silně alkalický pěnivý čistící přípravek.Používá se na odstranění tuků, napečenin atd. Vhodné zejména pro čištění v potravinářském průmyslu. Používá se na trouby, pece, konvektomaty, grily, atd. Pěnivý přípravek, který lze snadno opláchnout. Účinně odstraňuje mastnotu a nezanechává nepříjemný zápach. Neobsahuje fosfáty.",
        preicePerKg: "19400",
        pricePerKgVat: "23474",
        pricePerUnit: "116400",
        pricePerUnitVat: "140844",
        howToUse: "Aplikuje se pomocí nízkotlakového pěnovacího zařízení, rozprašovače apod. Teplota vody 0° - 80°C. Po aplikaci se přípravek nechá působit cca 5 minut. Před zaschnutím opláchnout čistou vodou. Nejlépe funguje při použití teplé vody. Po aplikaci musí být plochy, které přicházejí do styku s poživatinou opláchnuty dostatečným množstvím čisté vody. S opatrností může být používán na hliník a jiné alkalitám neodolné materiály.",
        dataSheet: "/downloads/rudon data.pdf",
        properties: "Nažloutlá kapalina, pH: 12-14 (1% roztok při 20 °C) Zápach: slabý.",
        safetySheet: "/downloads/rudon safety.pdf"
    },
    {
        id: 19,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "RUDON 30 kg",
        unit: "kg",
        amount: 30,
        shortDescription: "Pěnivý čistící přípravek na odstranění tuků, napečenin atd.",
        img: "/img/rudon 30.png",
        longDescription: "Silně alkalický pěnivý čistící přípravek.Používá se na odstranění tuků, napečenin atd. Vhodné zejména pro čištění v potravinářském průmyslu. Používá se na trouby, pece, konvektomaty, grily, atd. Pěnivý přípravek, který lze snadno opláchnout. Účinně odstraňuje mastnotu a nezanechává nepříjemný zápach. Neobsahuje fosfáty.",
        preicePerKg: "18100",
        pricePerKgVat: "21901",
        pricePerUnit: "543000",
        pricePerUnitVat: "657030",
        howToUse: "Aplikuje se pomocí nízkotlakového pěnovacího zařízení, rozprašovače apod. Teplota vody 0° - 80°C. Po aplikaci se přípravek nechá působit cca 5 minut. Před zaschnutím opláchnout čistou vodou. Nejlépe funguje při použití teplé vody. Po aplikaci musí být plochy, které přicházejí do styku s poživatinou opláchnuty dostatečným množstvím čisté vody. S opatrností může být používán na hliník a jiné alkalitám neodolné materiály.",
        dataSheet: "/downloads/rudon data.pdf",
        properties: "Nažloutlá kapalina, pH: 12-14 (1% roztok při 20 °C) Zápach: slabý.",
        safetySheet: "/downloads/rudon safety.pdf"
    },
    {
        id: 110,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "UNIPROF 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Čistící přípravek na okna, voděodolné povrchy, sanitární zařízení",
        img: "/img/uniprof 5.png",
        longDescription: "Efektivní koncentrovaný čisticí přípravek určený pro mytí oken bez leštění, každodenní údržbu voděodolných povrchových materiálů, plastových rámů oken, skříněk, stolů a parapetů. Vhodný pro pravidelné čištění většiny povrchových materiálů, jako je podlahová dlažba, parkety, plovoucí podlaha, linoleum, marmoleum, kámen atd.",
        preicePerKg: "18700",
        pricePerKgVat: "22627",
        pricePerUnit: "93500",
        pricePerUnitVat: "113135",
        howToUse: "Přípravek je určen pro ruční mytí. Je-li přípravek používán dle doporučení nezanechává po aplikaci na povrchu mapy po mytí. Dávkujte do teplé vody. Ruční mytí: okna, skla 3 ml na 10 litrů vody. Běžné znečištění: 0,5 dc na 10 litrů vody. Větší znečištění 1 dc na 10 litrů vody.",
        dataSheet: "",
        properties: "",
        safetySheet: "/downloads/uniprof grep safety.pdf"
    },
    {
        id: 111,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "Rambo písek 650 ml (14 ks)",
        unit: "ks",
        amount: 14,
        shortDescription: "Tekutý písek na mytí nádobí a čištění povrchů",
        img: "/img/rambo sand 0,650.png",
        longDescription: "Vysoce účinný tekutý písek pro mytí nádobí a čištění silně znečištěných povrchů různých materiálů. Obsah balení: 14 ks.",
        preicePerKg: "4200",
        pricePerKgVat: "5082",
        pricePerUnit: "58800",
        pricePerUnitVat: "71148",
        howToUse: "",
        dataSheet: "",
        properties: "",
        safetySheet: "/downloads/rambo sand safety.pdf"
    },
    {
        id: 112,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "RAMBO WC 750 ml (10 ks)",
        unit: "ks",
        amount: 10,
        shortDescription: "Kyselý čistič sanitárních zařízení a keramiky",
        img: "/img/rambo wc 0,750.png",
        longDescription: "Kyselý čistič (kachna) je určen k mytí a ošetřování sanitárních zařízení a keramiky. Je vhodný k odstraňování rzi a vodního kamene. Používá se na všechny kyselinovzdorné materiály, jako je porcelán, keramika apod. Efektivně odstraňuje i silné vrstvy vodního kamene. Obsah balení: 14 ks.",
        preicePerKg: "5800",
        pricePerKgVat: "7018",
        pricePerUnit: "58000",
        pricePerUnitVat: "70180",
        howToUse: "Používá se na jednorázový úklid. Přípravek se neředí.",
        dataSheet: "",
        properties: "",
        safetySheet: "/downloads/rambo wc safety.pdf"
    },
    {
        id: 113,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "RAMBO mléko 650 ml (14 ks)",
        unit: "ks",
        amount: 14,
        shortDescription: "Čistící mléko na ruce",
        img: "/img/rambo milk 0,650.png",
        longDescription: "Vysoce účinný prostředek k mytí silně znečištěných rukou zejména od šmíru, oleje, ale i dalšího znečištění.",
        preicePerKg: "4400",
        pricePerKgVat: "5324",
        pricePerUnit: "61600",
        pricePerUnitVat: "74536",
        howToUse: "Na zašpiněné ruce použijte potřebné množství přípravku a bez použití vody po dobu cca půl minuty ruce myjte, poté ruce opláchněte proudem tekoucí vody.",
        dataSheet: "",
        properties: "",
        safetySheet: ""
    },
];

/* Template
    {
        id: ,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "",
        unit: "",
        amount: ,
        shortDescription: "",
        img: "/img/canister.jpg",
        longDescription: "",
        preicePerKg: "",
        pricePerKgVat: "",
        pricePerUnit: "",
        pricePerUnitVat: "",
        howToUse: "",
        dataSheet: "",
        properties: "",
        safetySheet: ""
    },
*/