let specData = [   
    {
        id: 51,
        category: "Speciální prostředky",
        categoryColor: "#c13540",
        link: "store.html#special",
        productName: "Limescale Strong 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Silně kyselý čistící přípravek na rez a vodní kámen",
        img: "/img/limescale strong 5.png",
        longDescription: "<p>Silně kyselý, čistící přípravek na rez a vodní kámen. Je určen pro mytí železa, plastů, kamene, cihel, zámkové dlažby, porcelánu a jako kyselé mytí betonových podlah před nanesením epoxy vrstvy nebo podlahového nátěru.</p><p>Ideální k odstranění nečistot z betonovývh podlah s natřeným povrchem, strojů a zařízení. Je velmi účinný pro čištění kamenných dlaždic, zámkové dlažby, odstraňuje vodní kámen, zbytky betonových nánosů a rez.</p>",
        preicePerKg: "20900",
        pricePerKgVat: "25289",
        pricePerUnit: "104500",
        pricePerUnitVat: "126445",
        howToUse: "<p>Používá se neředěný nebo v poměru 1:1 – 1:10 do vody.</p><p>Po aplikaci opláchněte vodou (teplou), aby se povrch zneutralizoval.</p><p>Může odbarvit hliník, mosaz, měď a zinek.</p>",
        dataSheet: "/downloads/limescale strong data.pdf",
        properties: "<p>Modrá kapalina, pH 1,5-2,5 (3% roztok při 20 °C). Zápach: charakteristický.</p>",
        safetySheet: "/downloads/limescale strong safety.pdf"
    },
    {
        id: 52,
        category: "Speciální prostředky",
        categoryColor: "#c13540",
        link: "store.html#special",
        productName: "Limescale Strong 25 kg",
        unit: "kg",
        amount: 25,
        shortDescription: "Silně kyselý čistící přípravek na rez a vodní kámen",
        img: "/img/limescale strong 25.png",
        longDescription: "<p>Silně kyselý, čistící přípravek na rez a vodní kámen. Je určen pro mytí železa, plastů, kamene, cihel, zámkové dlažby, porcelánu a jako kyselé mytí betonových podlah před nanesením epoxy vrstvy nebo podlahového nátěru.</p><p>Ideální k odstranění nečistot z betonovývh podlah s natřeným povrchem, strojů a zařízení. Je velmi účinný pro čištění kamenných dlaždic, zámkové dlažby, odstraňuje vodní kámen, zbytky betonových nánosů a rez.</p>",
        preicePerKg: "18800",
        pricePerKgVat: "22748",
        pricePerUnit: "470000",
        pricePerUnitVat: "568700",
        howToUse: "<p>Používá se neředěný nebo v poměru 1:1 – 1:10 do vody.</p><p>Po aplikaci opláchněte vodou (teplou), aby se povrch zneutralizoval.</p><p>Může odbarvit hliník, mosaz, měď a zinek.</p>",
        dataSheet: "/downloads/limescale strong data.pdf",
        properties: "<p>Modrá kapalina, pH 1,5-2,5 (3% roztok při 20 °C). Zápach: charakteristický.</p>",
        safetySheet: "/downloads/limescale strong safety.pdf"
    },
];

/* Template
    {
        id: ,
        category: "Speciální prostředky",
        categoryColor: "#c13540",
        link: "store.html#special",
        productName: "",
        unit: "",
        amount: ,
        shortDescription: "",
        img: "/img/canister.jpg",
        longDescription: "<p></p>",
        preicePerKg: "",
        pricePerKgVat: "",
        pricePerUnit: "",
        pricePerUnitVat: "",
        howToUse: "<p></p>",
        dataSheet: "",
        properties: "<p></p>",
        safetySheet: ""
    },
*/